version: "3.8"

services:
  yolo-edge:
    build: ./yolo-edge
    image: ghcr.io/spectre200-4/ci-cd/yolo-edge:latest
    command: python app.py --source http://192.168.0.104:8080/video
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - edge-net

  dashboard:
    build: ./dashboard
    image: ghcr.io/spectre200-4/ci-cd/dashboard:latest
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - edge-net

  kafka:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
    environment:
      # Enable KRaft mode
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - CLUSTER_ID=ci-cd-cluster
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - edge-net

volumes:
  kafka-data:

networks:
  edge-net:
    driver: bridge
